<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<?php $lazyLoadHelper = $this->helper('WeltPixel\LazyLoading\Helper\Data');  ?>

<?php
$lazyLoadClass = '';
if ($block->getLazyLoad()) {
    $lazyLoadClass = 'owl-lazy';
} elseif ($lazyLoadHelper->isEnabled() && !$block->getOwlcarousel() ) {
    $lazyLoadClass = 'lazy';
}
?>
<img class="photo image <?php echo $lazyLoadClass; ?>"
    <?php /* @escapeNotVerified */ echo $block->getCustomAttributes(); ?>
    <?php if (!$block->getLazyLoad()): ?>
        <?php if ($lazyLoadHelper->isEnabled() && !$block->getOwlcarousel()) : ?>
            src="<?php /* @escapeNotVerified */ echo $lazyLoadHelper->getImageLoader(); ?>"
            data-original="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
        <?php else:  ?>
            src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
        <?php endif; ?>
    <?php endif; ?>
     width="<?php /* @escapeNotVerified */ echo $block->getWidth(); ?>"
     height="<?php /* @escapeNotVerified */ echo $block->getHeight(); ?>"
     alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>"
    <?php if ($block->getLazyLoad()): ?>
        data-src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
        data-src-retina="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
    <?php endif; ?>
/>
